// Generated by tool/generate_ios_sources.sh - do not edit.
// Forwards to third_party/zxing-cpp/core/src/BarcodeFormat.h so the search path can stay inside the Swift package.
#include "../../../../../third_party/zxing-cpp/core/src/BarcodeFormat.h"
