#!/usr/bin/env bash
#
# Regenerates the iOS forwarders under ios/lightweight_barcode_scanner/Sources/lbs_core.
#
# Neither build system can reach the shared C++ core directly:
#
#   * CocoaPods resolves `source_files` relative to the podspec and silently
#     drops anything outside it - the official `flutter create
#     --template=plugin_ffi` podspec says as much.
#   * Swift Package Manager is stricter still: sources must live inside the
#     package, and it rejects a header search path that escapes the package
#     root ("header search path should not be outside the package root").
#
# The shared core has to stay at the package root so the Android CMake build
# and the host tests compile the very same files, so everything the iOS build
# needs is mirrored into the package as one-line forwarders:
#
#   forwarders/     one .cpp per translation unit
#   vendor_include/ one .h per header, mirroring the upstream directory layout
#
# A quoted #include inside an included file is resolved against *that* file's
# real directory, so ZXing's own includes keep working unchanged; the mirrored
# headers only exist to give SPM a search path that stays inside the package.
#
# Run this after tool/vendor_zxing.sh (which calls it for you).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CORE="$ROOT/ios/lightweight_barcode_scanner/Sources/lbs_core"
SRC_DEST="$CORE/forwarders"
HDR_DEST="$CORE/vendor_include"

rm -rf "$SRC_DEST" "$HDR_DEST"
mkdir -p "$SRC_DEST" "$HDR_DEST"

# Number of "../" needed to climb from a file at $1 back to the package root.
up_to_root() {
  local dir="$1" rel prefix=""
  rel="${dir#"$ROOT/"}"
  local IFS=/
  for _ in $rel; do prefix="../$prefix"; done
  printf '%s' "$prefix"
}

sources=0
emit_source() {
  local rel="$1"                       # path relative to the package root
  local name="${rel#*/}"               # drop the leading directory
  name="${name//\//_}"                 # flatten: one directory, unique names
  local out="$SRC_DEST/lbs_$name"
  cat > "$out" <<EOF
// Generated by tool/generate_ios_sources.sh - do not edit.
// Compiles $rel as part of the iOS target.
#include "$(up_to_root "$SRC_DEST")$rel"
EOF
  sources=$((sources + 1))
}

headers=0
emit_header() {
  local rel="$1"                       # path relative to the package root
  local as="$2"                        # how the code spells the #include
  local out="$HDR_DEST/$as"
  mkdir -p "$(dirname "$out")"
  cat > "$out" <<EOF
// Generated by tool/generate_ios_sources.sh - do not edit.
// Forwards to $rel so the search path can stay inside the Swift package.
#include "$(up_to_root "$(dirname "$out")")$rel"
EOF
  headers=$((headers + 1))
}

# Translation units: the shared core plus the vendored ZXing reader.
while IFS= read -r file; do
  emit_source "${file#"$ROOT/"}"
done < <(find "$ROOT/src" -maxdepth 1 -name '*.cpp' | sort)

while IFS= read -r file; do
  emit_source "${file#"$ROOT/"}"
done < <(find "$ROOT/third_party/zxing-cpp/core/src" \
  \( -name '*.cpp' -o -name '*.c' \) | sort)

# Headers, spelled the way the sources include them.
while IFS= read -r file; do
  emit_header "${file#"$ROOT/"}" "$(basename "$file")"
done < <(find "$ROOT/src" -maxdepth 1 -name '*.h' | sort)

while IFS= read -r file; do
  emit_header "${file#"$ROOT/"}" "${file#"$ROOT/third_party/zxing-cpp/core/src/"}"
done < <(find "$ROOT/third_party/zxing-cpp/core/src" -name '*.h' | sort)

while IFS= read -r file; do
  emit_header "${file#"$ROOT/"}" "$(basename "$file")"
done < <(find "$ROOT/third_party/zxing-cpp/core/generated" -name '*.h' | sort)

echo "==> generated $sources source forwarders in ${SRC_DEST#"$ROOT/"}"
echo "==> generated $headers header forwarders in ${HDR_DEST#"$ROOT/"}"
