#!/usr/bin/env bash
#
# Regenerates ios/Classes/forwarders/.
#
# CocoaPods resolves `source_files` relative to the podspec and silently drops
# anything outside it - the official `flutter create --template=plugin_ffi`
# podspec says as much. The shared C++ core has to stay at the package root so
# the Android CMake build and the host tests compile the very same files, so
# each translation unit gets a one-line forwarder inside ios/Classes that
# #includes it.
#
# A quoted #include inside an included file is resolved against *that* file's
# real directory, so ZXing's own includes keep working unchanged.
#
# Run this after tool/vendor_zxing.sh (which calls it for you).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="$ROOT/ios/Classes/forwarders"

rm -rf "$DEST"
mkdir -p "$DEST"

count=0
emit() {
  local rel="$1"                       # path relative to the package root
  local name="${rel#*/}"               # drop the leading directory
  name="${name//\//_}"                 # flatten
  cat > "$DEST/lbs_$name" <<EOF
// Generated by tool/generate_ios_sources.sh - do not edit.
// Compiles $rel as part of the CocoaPods target.
#include "../../../$rel"
EOF
  count=$((count + 1))
}

while IFS= read -r file; do
  emit "${file#"$ROOT/"}"
done < <(find "$ROOT/src" -maxdepth 1 -name '*.cpp' | sort)

while IFS= read -r file; do
  emit "${file#"$ROOT/"}"
done < <(find "$ROOT/third_party/zxing-cpp/core/src" \
  \( -name '*.cpp' -o -name '*.c' \) | sort)

echo "==> generated $count iOS forwarders in ios/Classes/forwarders"
