// Generated by tool/generate_ios_sources.sh - do not edit.
// Compiles third_party/zxing-cpp/core/src/libzueci/zueci.c as part of the CocoaPods target.
#include "../../../third_party/zxing-cpp/core/src/libzueci/zueci.c"
