// Generated by tool/generate_ios_sources.sh - do not edit.
// Compiles third_party/zxing-cpp/core/src/qrcode/QRFormatInformation.cpp as part of the iOS target.
#include "../../../../../third_party/zxing-cpp/core/src/qrcode/QRFormatInformation.cpp"
